server:
  port: 8080
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health    
    
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
        timeout:
          enabled: false
            
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
  
zuul.routes.fares.serviceId: FARES
zuul.routes.productCatalog.serviceId: PRODUCTCATALOGRESP
zuul.routes.bffwebadmin.serviceId: BFFWEBADMIN
zuul.routes.metaDataCatalog.serviceId: METADATACATALOG
zuul.routes.customer.serviceId: CUSTOMER
zuul.routes.inventory.serviceId: INVENTORY
zuul.routes.shoppingCart.serviceId: SHOPPINGCART
zuul.routes.charging.serviceId: CHARGING
zuul.routes.charge.serviceId: CHARGE